### ISSUE TITLE
handle t_cleanup exception

### ISSUE THREAD

**Issue by cmoussa1** [cmoussa1/ba-lib-prototype#4]
Right now, when calling `write_to_db()` on jobs that are still active (i.e., don't have a `t_cleanup` field yet), a `KeyError` is generated when trying to access that field to write it to a DB:

```
Traceback (most recent call last):
  File "./get_jobs.py", line 166, in <module>
    main()
  File "./get_jobs.py", line 162, in main
    write_to_db(jobs)
  File "./get_jobs.py", line 58, in write_to_db
    job["t_cleanup"],
KeyError: 't_cleanup'
```

This exception should be handled to skip attempting to write that entry until it is finished.

**Comment by cmoussa1** [comment]
fixed by 4bb7655
